name: expense_tracker
description: A personal expense tracker app

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.3.6
  uuid: ^3.0.7
  intl: ^0.18.1
  fl_chart: ^0.62.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^14.1.1
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
